message("Running full replication:")
message("1. Importing and preparing data")
source("analysis/01_import_and_prepare.R")
message("2. Building genre trees")
source("analysis/02_build_genre_trees.R")
message("3. Tuning tree folding")
source("analysis/03_fold_metagenres.R")
message("4. Mapping metagenres")
source("analysis/04_map_metagenres.R")
message("5. Classifying metagenres")
source("analysis/05_classify_metagenres.R")
